# Generated by Django 5.2.7 on 2025-10-13 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_medico', models.CharField(choices=[('PLANTA', 'Médico de planta'), ('CONSULTOR', 'Consultor externo'), ('RESIDENTE', 'Residente')], default='PLANTA', max_length=15)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaz_clinica.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaz_clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaz_clinica.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interfaz_clinica.tiposangre'),
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('duracion_dias', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaz_clinica.consultamedica')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaz_clinica.medicamento')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaz_clinica.tratamiento')),
            ],
        ),
    ]
